import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="LCRA Executive Oversight", layout="wide", page_icon="⚡")

# Custom CSS for "Dark Mode" Enterprise Look
st.markdown("""
<style>
    .metric-card {
        background-color: #1E1E1E;
        padding: 20px;
        border-radius: 10px;
        border: 1px solid #333;
    }
    .metric-label { font-size: 14px; color: #888; }
    .metric-value { font-size: 28px; font-weight: bold; color: #FFF; }
    .status-ok { color: #4CAF50; } /* Green */
    .status-warn { color: #FFC107; } /* Amber */
    .status-crit { color: #FF5252; } /* Red */
</style>
""", unsafe_allow_html=True)

# --- 1. LOAD DATA ---
@st.cache_data
def load_data():
    # Load the 3 files generated by your previous script
    # Ensure these files are in the same folder as app.py
    try:
        df_projects = pd.read_csv("LCRA_Advanced_Project_Budgets.csv")
        df_timesheets = pd.read_csv("LCRA_Timesheets_1200.csv")
        df_status = pd.read_csv("LCRA_Project_Financial_Status.csv")
        return df_projects, df_timesheets, df_status
    except FileNotFoundError:
        st.error("❌ Data files not found. Please run the 'Master Data Generator' script first.")
        return None, None, None

df_projects, df_timesheets, df_status = load_data()

if df_status is not None:

    # --- SIDEBAR FILTERS ---
    st.sidebar.header("Filter Dashboard")
    status_filter = st.sidebar.multiselect("Project Status", options=["Active", "Closed"], default=["Active", "Closed"])
    
    # Filter Data based on Sidebar
    filtered_status_df = df_status[df_status['STATUS'].isin(status_filter)]
    
    # --- LEVEL 1: PORTFOLIO OVERVIEW ---
    st.title("⚡ LCRA Executive Oversight")
    st.markdown("### Level 1: Portfolio Health & Financials")

    # Metrics
    total_budget = filtered_status_df['TOTAL_BUDGET'].sum()
    total_spend = filtered_status_df['TOTAL_SPEND'].sum()
    pct_used = (total_spend / total_budget) * 100
    
    over_budget_count = len(filtered_status_df[filtered_status_df['PERCENT_USED'] > 100])
    near_budget_count = len(filtered_status_df[(filtered_status_df['PERCENT_USED'] >= 90) & (filtered_status_df['PERCENT_USED'] <= 100)])

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total Active Budget", f"${total_budget:,.0f}")
    with col2:
        st.metric("Total Consumed", f"${total_spend:,.0f}", delta=f"{pct_used:.1f}% Used", delta_color="inverse")
    with col3:
        st.metric("Critical Overruns (>100%)", f"{over_budget_count} Projects")
    with col4:
        st.metric("At Risk (90-100%)", f"{near_budget_count} Projects")

    # Charts Row
    c1, c2 = st.columns(2)
    
    with c1:
        st.subheader("Budget Burn by Project Status")
        fig_bar = px.bar(filtered_status_df, x="STATUS", y=["PRIOR_SPEND", "CURRENT_TIMESHEET_SPEND"], 
                         title="Prior Spend vs. Current Timesheet Burn",
                         color_discrete_sequence=["#3366CC", "#FF9900"])
        st.plotly_chart(fig_bar, use_container_width=True)

    with c2:
        st.subheader("Top 10 Highest Burn Rates (Current Period)")
        top_burners = filtered_status_df.nlargest(10, 'CURRENT_TIMESHEET_SPEND')
        fig_burn = px.bar(top_burners, x="CURRENT_TIMESHEET_SPEND", y="PROJECT_NAME", orientation='h',
                          color="PERCENT_USED", color_continuous_scale="RdYlGn_r",
                          title="Projects Burning Cash Fastest This Week")
        fig_burn.update_layout(yaxis={'categoryorder':'total ascending'})
        st.plotly_chart(fig_burn, use_container_width=True)

    st.divider()

    # --- LEVEL 2: PROJECT DRILL-DOWN ---
    st.markdown("### Level 2: Project Explorer")
    
    # Dropdown to select a project (Sorted by 'Critical' first)
    # We want to flag the ones that are Over Budget in the dropdown text
    
    def format_func(row):
        marker = "🔴" if row['PERCENT_USED'] > 100 else "🟢"
        return f"{marker} {row['PROJECT_ID']} - {row['PROJECT_NAME']} ({row['PERCENT_USED']}%)"

    project_options = filtered_status_df.sort_values('PERCENT_USED', ascending=False)
    selected_prj_id_raw = st.selectbox("Select Project to Drill Down:", project_options['PROJECT_ID'], 
                                   format_func=lambda x: format_func(project_options[project_options['PROJECT_ID'] == x].iloc[0]))

    # Get Selected Project Data
    selected_proj = df_status[df_status['PROJECT_ID'] == selected_prj_id_raw].iloc[0]

    # Display Project Header
    st.info(f"**Project Manager:** {df_projects[df_projects['PROJECT_ID']==selected_prj_id_raw]['PROJECT_MANAGER'].values[0]} | **Status:** {selected_proj['STATUS']}")

    # Gauge Chart for Budget
    fig_gauge = go.Figure(go.Indicator(
        mode = "gauge+number",
        value = selected_proj['PERCENT_USED'],
        title = {'text': "Budget Utilization (%)"},
        gauge = {
            'axis': {'range': [None, 120]},
            'bar': {'color': "black"},
            'steps': [
                {'range': [0, 90], 'color': "lightgreen"},
                {'range': [90, 100], 'color': "yellow"},
                {'range': [100, 120], 'color': "red"}],
            'threshold': {
                'line': {'color': "red", 'width': 4},
                'thickness': 0.75,
                'value': 100}}))
    
    p_col1, p_col2 = st.columns([1, 2])
    with p_col1:
        st.plotly_chart(fig_gauge, use_container_width=True)
    with p_col2:
        st.write("#### Financial Summary")
        st.dataframe(pd.DataFrame([selected_proj]).set_index('PROJECT_ID')[['TOTAL_BUDGET', 'TOTAL_SPEND', 'PRIOR_SPEND', 'CURRENT_TIMESHEET_SPEND']])

    st.divider()

    # --- LEVEL 3: TIMESHEET DETAILS ---
    st.markdown(f"### Level 3: Timesheet Audit Log for {selected_prj_id_raw}")
    
    # Filter Timesheets for this Project
    ts_data = df_timesheets[df_timesheets['PROJECT_ID'] == selected_prj_id_raw]

    if not ts_data.empty:
        # Metrics for this view
        total_hours = ts_data['HOURS'].sum()
        avg_rate = ts_data['BILL_RATE'].mean()
        
        m1, m2, m3 = st.columns(3)
        m1.metric("Total Hours Logged", f"{total_hours}")
        m2.metric("Avg. Bill Rate", f"${avg_rate:.2f}")
        m3.metric("Contractors Active", f"{ts_data['EMPLID'].nunique()}")
        
        # The Table
        st.dataframe(
            ts_data[['WORK_DATE', 'NAME', 'FIRM', 'TRC', 'HOURS', 'BILL_RATE', 'TOTAL_COST']]
            .sort_values('WORK_DATE', ascending=False)
            .style.background_gradient(subset=['TOTAL_COST'], cmap="Reds"),
            use_container_width=True
        )
    else:
        st.warning("No timesheets found for this project in the current period.")

else:
    st.write("Waiting for data...")
